.\" Manpage for libbaalue
.\" Contact thorsten.johannvorderbrueggen@t-online.de to correct errors or typos.
.TH libbaalue 3 "11 Oct 2015" "0.0.2" "libbaalue man page"
.SH NAME
libbaalue
\-\- some useful functions
.SH SYNOPSIS
.PP
#include \fI <libbaalue.h>\fP 
.PP
tbd ... void func_a(void);
.br
tbd ... void func_b(void);
.br
.PP
.SH DESCRIPTION
This functions are part of the  
.BR baalue_sdk
(https://github.com/tjohann/libbaalue)
.PP
The functions implement some useful functions
.PP
.SH FILES
.BR libbaalue.c 
\- function implementation
.br
.BR libbaalue.h 
\- interface header 
.br 
.PP
.SH OPTIONS
None
.PP
.SH BUGS
No known bugs
.PP
.SH "SEE ALSO"
.BR baalue(1)
.PP
.BR baalued(1)
.PP
.SH AUTHOR
Thorsten Johannvorderbrueggen 
.br
Email: \fB<thorsten.johannvorderbrueggen@t-online.de> \fP

