.\" Manpage for libbaalue
.\" Contact thorsten.johannvorderbrueggen@t-online.de to correct errors or typos.
.TH libbaalue 1 "11 Oct 2015" "0.0.1" "libbaalue man page"
.SH NAME
libbaalue
\-\- the libbaalue
.SH SYNOPSIS
.PP
.SH DESCRIPTION
This functions are part of the
.BR Bananapi (CAN) Cluster
(https://github.com/tjohann/libbaalue)
.PP
The base library libbaalue
.PP
.SH FILES
.BR libbaalue.so
\- function implementation
.br
.BR libbaalue.h
\- interface header
.br
.PP
.SH OPTIONS
None
.PP
.SH BUGS
No known bugs
.PP
.SH "SEE ALSO"
.BR baalued(1)
.PP
.BR baalue(1)
.PP
.SH AUTHOR
Thorsten Johannvorderbrueggen
.br
Email: \fB<thorsten.johannvorderbrueggen@t-online.de> \fP
