#
# my simple libconfig cmake file
#

FIND_PATH(LIBCONFIG_INCLUDE_DIR libconfig.h PATH_SUFFIXES config)

FIND_LIBRARY(LIBCONFIG_LIBRARY config)
IF(LIBCONFIG_LIBRARY)
    SET(LibCONFIG_FOUND TRUE)
ENDIF()

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibCONFIG DEFAULT_MSG LIBCONFIG_LIBRARY LIBCONFIG_INCLUDE_DIR)